### ISSUE TITLE
Sample project does not build on Android Studio 4.0

### ISSUE THREAD

**Issue by JamesNitsch** [simonnorberg/kortholt#2]
Project and sample worked fine on older versions of Android Studio up to 3.6.

Since upgrading to Android Studio 4.0, which forces use of gradle 4.0.0-alpha09, I'm getting the following error during compilation:

```
> Task :kortholt:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kortholt:externalNativeBuildDebug'.
> Source /Users/jamesnitsch/kortholt/kortholt/build/intermediates/cmake/debug/obj/x86/libpd.so and destination /Users/jamesnitsch/kortholt/kortholt/build/intermediates/cmake/debug/obj/x86/libpd.so must be different

```

I'm going to try to look into it, but wanted to bring it up here in case you happen to have a solution in mind. It does not seem to be a simple case of clean / invalidate caches / restart.

**Comment by simonnorberg** [comment]
The project has been updated to use Gradle plugin 4.0.0-beta01 and NDK 21. It should work now.

**Comment by JamesNitsch** [comment]
Thank you, an upgrade and clean build of the project installs successfully. 

I tried my hand at fixing this, but the error given by Gradle didn't give any hint that the version of the NDK was the issue. In hindsight it makes a lot of sense, but I'm curious how you arrived at that solution, or if it was just a hunch.
