### ISSUE TITLE
Question - Is it possible that a receiver can be registered in the sample app

### ISSUE THREAD

**Issue by xcubik** [simonnorberg/kortholt#4]
I'm trying to add a receiver to PdBase to get the messages from puredata.
Did you test that or is this not possible?

I tried the following in the sample-app:

in onCreate:

        PdBaseHelper
        PdBase.setReceiver(receiver)
        PdBaseHelper.openPatch(this, R.raw.test, "test.pd")

    private val receiver: PdReceiver = object : PdReceiver {
        private fun pdPost(msg: String) {
            Timber.v("### pdPost: $msg")
        }
        override fun print(s: String) {
            Timber.v("### print: $s")
        }
        override fun receiveBang(source: String) {
            pdPost("bang: $source")
        }
        override fun receiveFloat(source: String, x: Float) {
            pdPost("float: $source | $x")
        }
        override fun receiveList(source: String, vararg args: Any) {
            pdPost("list: $source | " + args.contentToString())
        }
        override fun receiveMessage(source: String, symbol: String, vararg args: Any) {
            pdPost("message: $source | " + args.contentToString())
        }
        override fun receiveSymbol(source: String, symbol: String) {
            pdPost("symbol: $source | $symbol")
        }
    }

**Comment by simonnorberg** [comment]
It should be possible. The messages can be received by polling `PdBase.pollPdMessageQueue()`.

[Here is an example](https://github.com/libpd/pd-for-android/blob/master/PdCore/src/main/java/org/puredata/android/io/PdAudio.java#L30-L37).

**Comment by xcubik** [comment]
Thank you, this is working
